### ISSUE TITLE
Webpack 3 support

### ISSUE THREAD

**Issue by langri-sha** [vseventer/sharp-image-loader#1]
I've had some issues with Webpack 3, namely getting wrong paths passed to `sharp`. But upgrading the packages (most importantly, the `loader-utils`). It seems to have done the trick and everything is working again.

**Comment by vseventer** [comment]
Thank you for your report - I'll look into this.

**Comment by vseventer** [comment]
After investigating, this plugin receives the raw source, and modifies this. At no point is a filename used, therefore I suspect this error is originating from webpack or another plugin. Feel free to submit reproducing code. Closing for now.

**Comment by langri-sha** [comment]
Hmm, well I moved from my exotic fork back to the base repo and I'm getting errors in  `libvips.so` again somehow. Well, if anyone else gets issues in Webpack 3, hope they post here 🔍.
