### ISSUE TITLE
Running sharp-image-loader on an image twice throws error

### ISSUE THREAD

**Issue by thasmo** [vseventer/sharp-image-loader#2]
When running the `sharp-image-loader` on the same source image twice (or more), an error is thrown:
```
Module build failed: Error: Input buffer contains unsupported image format
    at Error (native)
```
This happens when the `sharp-image-loader` is defined twice (or more) with different options.

Is there a way to prevent this?

**Comment by thasmo** [comment]
This throws an error:
```js
    {
        module: {
            rules: [{
                test: /icon\.png/,
                use: [
                    'file-loader',
                    {
                        loader: 'sharp-image-loader',
                        options: {
                            height: 16,
                            width: 16,
                        },
                    },
                ],
            }, {
                test: /icon\.png/,
                use: [
                    'file-loader',
                    {
                        loader: 'sharp-image-loader',
                        options: {
                            height: 32,
                            width: 32,
                        },
                    },
                ],
            }],
        },
    }
```
Is it a bug or do I need to configure it differently?

**Comment by thasmo** [comment]
Pingin' @vseventer to ensure this doesn't get lost in space or beyond. 🚀

**Comment by vseventer** [comment]
@thasmo What are you trying to achieve? This module is meant to create an edited version of a single image, not create multiple images, which judging from your `test` looks like you're trying to do?

**Comment by thasmo** [comment]
@vseventer I want to create multiple versions (which differ in size) from a single source image.

**Comment by vseventer** [comment]
For this purpose, I think you'll have better luck trying something like [responsive-loader](https://www.npmjs.com/package/responsive-loader).
